name: CI
on: 
  push: 

jobs:     
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Enable Flutter Web
        run: flutter config --enable-web 
      - name: Install Dependencies
        run: flutter pub get
      - name: Run Build Runner
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Format
        run: flutter format --set-exit-if-changed .
      - name: Analyze
        run: flutter analyze .
      - name: Run tests
        run: flutter test --coverage
      - name: Check Code Coverage
        uses: VGVentures/very-good-coverage@v1.1.0
        with:
          path: ./coverage/lcov.info
          min_coverage: 70
          exclude: "**/*.freezed.dart *.iconfig.dart /lib/config/config.dart"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build Web
        run: flutter build web --dart-define=mode=production
